apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: maven-app 
spec: 
  replicas: 2 
  selector: 
    matchLabels: 
      app: maven-app 
  template: 
    metadata: 
      name: maven-web-app 
      labels: 
        app: maven-app 
    spec: 
      containers: 
      - name: mavenappcontainer 
        image: frankystar1/maven-web-app:1
        ports: 
        - containerPort: 8080 
        env: 
        - name: MONGO_DB_USERNAME 
          value: devdb 
        - name: MONGO_DB_PASSWORD 
          value: devdb@123 
        - name: MONGO_DB_HOSTNAME 
          value: mongo  
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: mavensvc 
spec: 
  selector: 
    app: maven-app 
  ports: 
  - port: 80 
    targetPort: 8080 
  type: LoadBalancer 

